spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      pool-name: DBConnectionPool
      leak-detection-threshold: 500000
      connection-test-query: SELECT 1
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: false
  redis:
    host: 127.0.0.1
    port: 6389
    database: 0
    test-on-borrow: false
    timeout: 85000
    address: redis://127.0.0.1:6379
    lettuce:
      max-active: 1024
      max-wait: 3000
      max-idle: 50
      min-idle: 5
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG